### ISSUE TITLE
Using this in member initilization puts an extra period in front of self

### ISSUE THREAD

**Issue by DataEncoded** [roblox-csharp/roblox-cs#8]
When using `this` in method initialization, an extra dot is placed in front of the self variable.
C#:
```cs
this.tag = remoteTag;
```
converts to
```luau
.self.tag = remoteTag
```
However, if you don't use this.tag, and just convert it to 
```cs
tag = remoteTag
```
it converts correctly
```luau
self.tag = remoteTag
```

While using `this` in `this.tag = remoteTag` is useless, it is needed for something like `this.tag = tag` if the tag is used in an constructor with a parameter of the same name.

**Comment by R-unic** [comment]
Damn I thought about this the other day and forgot about it. Will be fixed soon.
